# Ref: https://stackoverflow.com/questions/59770919/travis-builds-failing-due-to-rstan-compilation-issues

language: r
r:
  - release
  - devel
latex: true
warnings_are_errors: TRUE

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libproj-dev
      - libmpfr-dev

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=true
    - _R_CHECK_CRAN_INCOMING_=true

cache:
  - packages
  - ccache

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

r_packages:
  - Rcpp
  - RcppEigen
  - RcppArmadillo
  - BH
  - mvtnorm
  - rstan
  - StanHeaders
  - rstantools
  - dplyr
  - tidyr
  - tibble
  - ggplot2
  - rlang
  - vctrs
  - testthat
  - devtools
  - remotes
  - knitr
  - rmarkdown
  - mrgsolve


before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fext-numeric-literals -fPIC" >> ~/.R/Makevars

notifications:
  email:
  on_success: change
  on_failure: change

script:
  - |
    travis_wait 42 R CMD build .
    travis_wait 59 R CMD check rstanemax*tar.gz

after_script:
  - tar -ztvf rstanemax_*.tar.gz
  - echo ${NOT_CRAN}

after_failure:
  - cat rstanemax.Rcheck/00*
